### ISSUE TITLE
new feature?

### ISSUE THREAD

**Issue by mrc4tt** [dejavueakay/orangebot#4]
Hi,

is there planned for adding supporting !admin [msg] via discord e.g?

**Comment by huytc** [comment]
Wonder if this is still maintained :(

**Comment by mrc4tt** [comment]
i dont think it's maintained anymore. because there is weird bugs on orangebot.. like BO3.. where the 1stmap works fine. but 2ndmap is bugged.. where all players got "guns" after starting.. it should be knife.. no no.. "real guns" xD

**Comment by dejavueakay** [comment]
hey guys :)

sorry i've been really busy with other projects + university

@MikkeIDK: Unfortunately i'm not planning to touch discord.

@huytc: is there something i can do for you? if it's not that big maybe i can implement it or hint you to the solution (if you have experience with javascript)

**Comment by mrc4tt** [comment]
@dejavueakay it's alright. i have found some bugs.. dunno about it can be fixed from you? :D

**Comment by huytc** [comment]
@dejavueakay: Thanks for the reply. Not really anything, I'm just wondering. I've been using and customizing Orangebot for quite a while now :D Thank you.

**Comment by mrc4tt** [comment]
btw @dejavueakay are you still active? - about you maybe can looking, why the orangebot don't starting/ from 2ndmap e.g !start de_dust2 de_inferno de_nuke > and it wont starting with scores from the de_nuke.

Thanks ;)

**Comment by dejavueakay** [comment]
Hi there!

I still actively play CS:GO, but unfortunately due to university i lack the time to do any side projects :(

I'm sorry i cannot imagine what the problem might be because i have tested that feature and did not find any bugs - what do you mean exactly by "scores from de_nuke"?

Am 03.02.2019 um 20:14 schrieb Mikkel <notifications@github.com<mailto:notifications@github.com>>:


btw @dejavueakay<https://github.com/dejavueakay> are you still active? - about you maybe can looking, why the orangebot don't starting/ from 2ndmap e.g !start de_dust2 de_inferno de_nuke > and it wont starting with scores from the de_nuke.

Thanks ;)

**Comment by mrc4tt** [comment]
Hi @dejavueakay 

It's because if you are starting the orangebot on the server.
And setting the server to starting with 3 maps - for example, de_dust2, de_nuke, de_inferno.

I have experienced when I finish the first map and move on to the next map, so it should work without the score itself being fucked up.
**About the bug of BO3**:
I did started with: mirage, nuke, cache
Mirage: Console: Counter-Terrorists won the knife round!
Console: Do you want to !stay or !swap?
● mrc4t‎ : !swap
mrc4t is joining the Terrorist force
● mrc4t‎ : !status
Console: mix1 [de_mirage 0-1, de_inferno x-x, de_cache x-x] mix2 << Here is the problem. after the knife, it will shot 0-1, but not 0-0 when it's started! - What 2 do?
